// frontend/widgets/comments/src/components/comment/comment-votes.svelte
<script lang="ts">
	import { t } from '../../lib/i18n'
	import { voteForComment } from '../../stores/comments'
	import Icon from '../ui/icons/icon.svelte'

	export let id: string
	export let vote: 0 | -1 | 1
	export let score: number
	export let disabled: boolean | undefined = undefined

	// let errorMessage: string | undefined

	$: isUpvoted = vote === 1
	$: isDownvoted = vote === -1
	$: value = loadingState?.score ?? score
	// isPositiveScore = StaticStore.config.positive_score && value > -1;
	$: isPositiveScore = false
	$: downvoteIsDisabled = loadingState !== null || isDownvoted || isPositiveScore

	let loadingState: { vote: number; score: number } | null = null

	async function handleClick(evt: MouseEvent) {
		const { value } = (evt.currentTarget as HTMLButtonElement).dataset
		const increment = Number(value) as -1 | 1

		loadingState = { vote: vote + increment, score: score + increment }

		try {
			await voteForComment(id, increment)
			// errorMessage = undefined
			setTimeout(() => {
				loadingState = null
			}, 200)
		} catch (err) {
			// setErrorMessage(extractErrorMessageFromResponse(err, intl))
			// errorMessage = err instanceof Error ? err.message : t('Something went wrong')
			loadingState = null
		}
	}

	// export const messages = defineMessages({
	//   score: {
	//     id: 'vote.score',
	//     defaultMessage: 'Votes score',
	//   },
	//   upvote: {
	//     id: 'vote.upvote',
	//     defaultMessage: 'Vote up',
	//   },
	//   downvote: {
	//     id: 'vote.downvote',
	//     defaultMessage: 'Vote down',
	//   },
	//   controversy: {
	//     id: 'vote.controversy',
	//     defaultMessage: 'Controversy: {value}',
	//   },
	// }); -->
</script>

<span class="votes" class:votes-disabled={disabled}>
	{#if !disabled}
		<button
			class="vote-button vote-button_downvote"
			class:vote-button_downvote-active={isDownvoted}
			on:click={handleClick}
			data-value={-1}
			title={$t('Vote down')}
			disabled={downvoteIsDisabled}
		>
			<Icon name="chevron" />
		</button>
	{/if}
	<div
		class="score"
		class:positive-score={score > 0}
		class:negative-score={score < 0}
		title={$t('Votes score')}
	>
		{value}
	</div>
	{#if !disabled}
		<button
			class="vote-button vote-button_upvote"
			class:vote-button_upvote-active={isUpvoted}
			on:click={handleClick}
			data-value={1}
			title={$t('Vote up')}
			disabled={loadingState !== null || isUpvoted}
		>
			<Icon name="angle" />
		</button>
	{/if}
</span>

<style lang="postcss">
	.votes {
		@apply flex items-center font-bold select-none;
	}

	.votes-disabled {
		@apply justify-center;
	}

	.vote-button {
		@apply flex items-center p-1 h-6 w-6 opacity-40;
		transition: opacity 0.15s color 0.15s;
	}

	.votes:hover .vote-button {
		@apply opacity-100;
	}

	.vote-button_upvote :global(svg) {
		@apply rotate-180;
	}

	.vote-button_upvote:hover,
	.vote-button_upvote-active {
		@apply opacity-100;
	}

	.vote-button_downvote:hover,
	.vote-button_downvote-active {
		@apply opacity-100;
	}

	.score {
		@apply mx-1 p-1 font-bold rounded min-w-[2rem] text-center;
	}

	.negative-score {
		@apply bg-red-500/10 dark:text-red-600;
	}

	.positive-score {
		@apply bg-green-500/10 dark:text-green-600;
	}

	/* .errorMessage {
		white-space: nowrap;
		font-weight: 500;
	} */
</style>

// frontend/apps/remark42/app/components/comment/comment-votes.tsx
import clsx from 'clsx';
import { h } from 'preact';
import { useState } from 'preact/hooks';
import { defineMessages, useIntl } from 'react-intl';

import { useDispatch } from 'store/context';
import { patchComment } from 'store/comments/actions';
import { putCommentVote } from 'common/api';
import { StaticStore } from 'common/static-store';
import { ArrowIcon } from 'components/icons/arrow';

import styles from './comment-votes.module.css';
import { Tooltip } from 'components/tooltip';
import { extractErrorMessageFromResponse } from 'utils/errorUtils';

type Props = {
  id: string;
  vote: 0 | -1 | 1;
  votes: number;
  controversy: number | undefined;
  disabled?: boolean;
};

export function CommentVotes({ id, votes, vote, disabled }: Props) {
  const intl = useIntl();
  const dispatch = useDispatch();
  const [loadingState, setLoadingState] = useState<{ vote: number; votes: number } | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | void>(undefined);

  async function handleClick(evt: preact.JSX.TargetedEvent<HTMLButtonElement>) {
    const { value } = evt.currentTarget.dataset;
    const increment = Number(value) as -1 | 1;

    setLoadingState({ vote: vote + increment, votes: votes + increment });
    try {
      const p = await putCommentVote({ id, vote: increment });
      dispatch(patchComment({ ...p, vote: (vote + increment) as -1 | 0 | 1 }));
      setErrorMessage(undefined);
      setTimeout(() => setLoadingState(null), 200);
    } catch (err) {
      setErrorMessage(extractErrorMessageFromResponse(err, intl));
      setLoadingState(null);
    }
  }

  const isUpvoted = vote === 1;
  const isDownvoted = vote === -1;
  const value = loadingState?.votes ?? votes;
  const isPositiveScore = StaticStore.config.positive_score && value > -1;

  return (
    <span className={clsx(styles.root, disabled && styles.rootDisabled)}>
      {Boolean(!disabled) && (
        <button
          className={clsx(styles.voteButton, styles.downVoteButton, isDownvoted && styles.downVoteButtonActive)}
          onClick={handleClick}
          data-value={-1}
          title={intl.formatMessage(messages.downvote)}
          disabled={loadingState !== null || isDownvoted || isPositiveScore}
        >
          <ArrowIcon className={styles.downVoteIcon} />
        </button>
      )}
      <Tooltip
        content={errorMessage ? <div class={styles.errorMessage}>{errorMessage}</div> : undefined}
        position="top-left"
        hideBehavior="mouseleave"
        hideTimeout={10000}
        permanent
        onHide={() => {
          setErrorMessage(undefined);
        }}
      >
        <div
          title={intl.formatMessage(messages.score)}
          // title={intl.formatMessage(messages.controversy, { value: controversy })}
          className={clsx(styles.votes, {
            [styles.votesNegative]: votes < 0,
            [styles.votesPositive]: votes > 0,
          })}
        >
          {value}
        </div>
      </Tooltip>
      {!disabled && (
        <button
          className={clsx(styles.voteButton, styles.upVoteButton, isUpvoted && styles.upVoteButtonActive)}
          onClick={handleClick}
          data-value={1}
          title={intl.formatMessage(messages.upvote)}
          disabled={loadingState !== null || isUpvoted}
        >
          <ArrowIcon className={styles.upVoteIcon} />
        </button>
      )}
    </span>
  );
}

export const messages = defineMessages({
  score: {
    id: 'vote.score',
    defaultMessage: 'Votes score',
  },
  upvote: {
    id: 'vote.upvote',
    defaultMessage: 'Vote up',
  },
  downvote: {
    id: 'vote.downvote',
    defaultMessage: 'Vote down',
  },
  controversy: {
    id: 'vote.controversy',
    defaultMessage: 'Controversy: {value}',
  },
});
